Repository pi-hole/pi-hole, pull requests merged in 2018-11, with the labels that each got.

#2436 Fix error when reading in new password
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/webpage.sh
Labels: Bug: fixed

#2486 Beginning steps to installer overhaul. Echos to Printf test.
  automated install/basic-install.sh
Labels: pr: Approved

#2384 Set FTL Privacy Level During Install
  automated install/basic-install.sh
  test/test_automated_install.py
Labels: pr: Code Review Required

#2488 Moved `command -v` calls to function in installer.
  automated install/basic-install.sh
Labels: pr: Code Review Required

#2492 IPv4 detection improvements.
  automated install/basic-install.sh
Labels: pr: Approved

#2481 Revert "lighttpd conf enhancements"
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
Labels: pr: Approval Required

#2477 fix debug service check via sysvinit
  advanced/Scripts/piholeDebug.sh
Labels: pr: Code Review Required

#2497 Bugfix for #2354
  automated install/basic-install.sh
Labels: Bug: fixed

#2502 Release/v4.1 backports to development
  automated install/basic-install.sh
Labels: pr: Approved

#2500 Remove dnsmasq checks from debugger
  advanced/Scripts/piholeDebug.sh
Labels: Bug: fixed

#2501 Fix restartDNS returning code 1 even when it worked
  pihole
Labels: Bug: fixed

#2505 Account for non-standard ports in DNS server addresses.
  gravity.sh
Labels: Documented, pr: Approved

#2514 Suppress warning if Pi-hole is not used as DHCP server
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed

#2520 Backend changes for DHCPv4 rapid commit support
  advanced/Scripts/webpage.sh
Labels: Enhancement
