Repository pi-hole/pi-hole, pull requests merged in 2018-02, with the labels that each got.

#1962 Fixes https://github.com/pi-hole/pi-hole/issues/1772
  automated install/basic-install.sh
Labels: Bug fix

#1943 Pi-hole v3.3
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  CONTRIBUTING.md
  README.md
  advanced/01-pihole.conf
  advanced/Scripts/chronometer.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/webpage.sh
  advanced/pihole-FTL.service
  advanced/pihole.cron
  automated install/basic-install.sh
  gravity.sh
  pihole
Labels: Release

#1973 Don't auto-whitelist blocking list domains
  gravity.sh
Labels: Enhancement

#1929 pihole -f: Flush database
  advanced/Scripts/piholeLogFlush.sh
  automated install/basic-install.sh
Labels: Bug fix

#1981 Always replace pihole-FTL.service
  automated install/basic-install.sh
Labels: Bug fix

#1996 Specifty `LC_ALL=C` when dealing with sorted lists.
  gravity.sh
Labels: Bug fix, pr: Approved

#2000 Use pushd/popd and create random temporary directory
  automated install/basic-install.sh
Labels: Security, pr: Approved
