Repository pi-hole/pi-hole, pull requests merged in 2018-04, with the labels that each got.

#1987 Proper output for debug CPU detection
  advanced/Scripts/piholeDebug.sh
Labels: pr: ready for merge

#2056 Pi-hole core v3.3.1
  .pullapprove.yml
  advanced/Scripts/list.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/webpage.sh
  advanced/index.php
  automated install/basic-install.sh
  gravity.sh
Labels: Release

#2085 Backend changes needed to be able to set the privacy level
  advanced/Scripts/webpage.sh
Labels: Enhancement

#2105 Do not require DCO for Pi-hole Org members with GPG signed commits.
  .github/dco.yml
Labels: pr: Approved

#2108 Fix sed: can't read /etc/pihole/pihole-FTL.conf: No such file or directory
  advanced/Scripts/piholeLogFlush.sh
Labels: pr: Approved, pr: ready for merge

#2116 Check for new updates without actually updating
  advanced/Scripts/update.sh
  pihole
Labels: pr: Approval Required, pr: Code Review Required

#2027 Prevent inadvertent blocking of good domains appearing in query strings
  gravity.sh
Labels: pr: Approved

#2049 update donation and affiliate links. also link to trademark guideline…
  README.md
Labels: pr: Approval Required, pr: Code Review Required

#2126 Add backend changes for supporting a local DNS server
  advanced/Scripts/webpage.sh
Labels: Enhancement

#2133 Fix: add psmisc as dependency
  automated install/basic-install.sh
Labels: pr: Approved, pr: ready for merge

#2115 --disable-install-webserver
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/update.sh
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: pr: Approval Required, pr: Code Review Required

#2145 Add missing `/` to line 1511
  automated install/basic-install.sh
Labels: pr: Approved

#2140 Use domain list format for black.list and gravity.list
  gravity.sh
Labels: Enhancement, pr: Approved

#2147 Restore functionality to `pihole -up` broken in #2115
  advanced/Scripts/update.sh
Labels: pr: Approved

#2142 Fix static IP checking on Fedora
  automated install/basic-install.sh
Labels: pr: Approval Required, pr: Code Review Required

#2155 No need to stop services
  automated install/basic-install.sh
Labels: pr: Approval Required

#2123 Remove default blocklists from install
  adlists.default
  automated install/basic-install.sh
  gravity.sh
Labels: pr: Approval Required, pr: Code Review Required

#2157 Allow for empty/non existent adlist file
  gravity.sh
Labels: pr: Approval Required, pr: Code Review Required

#2159 Tweak/remove dnsmasq refs
  automated install/basic-install.sh
Labels: pr: Approval Required, pr: Code Review Required
