Repository pi-hole/pi-hole, pull requests merged in 2018-12, with the labels that each got.

#2531 Don't `mv` `preEventHorizon`, copy it.
  gravity.sh
Labels: Bug: fixed, Priority: High, pr: Approval Required

#2532 Update user agent string
  gravity.sh
Labels: Nice to have

#2504 configure ifcfg network files by connection name when required
  automated install/basic-install.sh
Labels: pr: Code Review Required

#2496 Release v4.1
  README.md
  advanced/01-pihole.conf
  advanced/Scripts/chronometer.sh
  advanced/Scripts/list.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/pihole-FTL.conf
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  advanced/index.php
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  pihole
  test/test_automated_install.py
  test/test_centos_fedora_support.py
Labels: Release

#2543 Add privacy level 4 to all privacy level code
  advanced/Scripts/webpage.sh
  advanced/bash-completion/pihole
  manpages/pihole-FTL.conf.5
  manpages/pihole.8
Labels: Bug: fixed

#2556 Release v.4.1.1
  automated install/basic-install.sh
Labels: Release

#2547 Don't show web version in pihole -v output if not installed
  advanced/Scripts/version.sh
Labels: Bug: fixed
