Repository pi-hole/pi-hole, pull requests merged in 2018-08, with the labels that each got.

#2322 Git Flow - Release/v4.0 merge back to development.
  advanced/Scripts/list.sh
  advanced/Scripts/wildcard_regex_converter.sh
  advanced/Templates/logrotate
  advanced/Templates/pihole-FTL.conf
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  advanced/Templates/pihole.sudo
  automated install/basic-install.sh
  gravity.sh
  manpages/pihole.8
Labels: Internal

#2329 Remove PowerPC from FTL binaries
  automated install/basic-install.sh
Labels: Bug: fixed

#2320 set noninteractive during unattended install
  automated install/basic-install.sh
Labels: Bug: fixed

#2343 Add facility to add multiple audit list entries at once and to nuke audit list
  advanced/Scripts/webpage.sh
Labels: Enhancement

#2358 Restart pihole-FTL after log flushing
  advanced/Scripts/piholeLogFlush.sh
Labels: Bug: fixed

#2382 Don't use extra query logging
  advanced/01-pihole.conf
Labels: Enhancement

#2378 Start pihole-FTL as root if capabilities are not supported by the system
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed

#2381 Improve /etc/dnsmasq.conf handling
  automated install/basic-install.sh
Labels: Bug: fixed

#2394 Ensure proper unprivileged user if pihole-FTL is started as root
  advanced/01-pihole.conf
Labels: Bug: fixed

#2356 Change the enable/disable method
  advanced/Scripts/list.sh
  gravity.sh
  pihole
Labels: Enhancement

#2398 WIP: Update RPM distro checks
  automated install/basic-install.sh
  test/test_centos_fedora_support.py
Labels: WIP
