Repository pi-hole/pi-hole, pull requests merged in 2018-09, with the labels that each got.

#2407 Fix lighttpd v1.4.50 crashing on startup
  automated install/basic-install.sh
Labels: Bug: fixed

#2299 Use ip route rather than old net-tools route in chronometer.sh
  advanced/Scripts/chronometer.sh
  automated install/basic-install.sh
Labels: Enhancement, Submitter Attention Required, Testing Required, pr: Approval Required

#2434 Only check web versions if web interface is installed
  advanced/Scripts/updatecheck.sh
Labels: pr: Approval Required, pr: Code Review Required
