Repository pi-hole/pi-hole, pull requests merged in 2018-05, with the labels that each got.

#2162 Don't attempt to download non-existent FTL Binary
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/update.sh
  automated install/basic-install.sh
Labels: pr: Approval Required, pr: Code Review Required

#2163 Fix for an error message introduced in #2162
  automated install/basic-install.sh
Labels: pr: Approval Required

#2169 Remove LOCAL_DNS_PORT support
  advanced/Scripts/webpage.sh
Labels: Enhancement

#2158 Update FTLDNS from dev
  README.md
  adlists.default
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/update.sh
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
Labels: pr: Approval Required

#2070 Get user locale when debugging
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approved

#1761 Tweak/uninstall
  automated install/uninstall.sh
Labels: Bug: fixed

#2057 debug script: fix empty ports on some systems
  advanced/Scripts/piholeDebug.sh
Labels: Bug: fixed, pr: Approval Required, pr: Code Review Required

#2167 flip uninstall compatability check
  automated install/uninstall.sh
Labels: pr: Approval Required

#1954 Prevent redundant entries from being added to Adlists.list
  advanced/Scripts/webpage.sh
Labels: Bug: fixed, pr: Approval Required, pr: Code Review Required
