Repository pi-hole/pi-hole, pull requests merged in 2018-07, with the labels that each got.

#2257 Move processWildcards to query.sh
  advanced/Scripts/query.sh
  pihole
Labels: Bug: fixed

#2236 Use regex lists instead of wildcards for blocking
  advanced/Scripts/list.sh
  advanced/Scripts/wildcard_regex_converter.sh
  gravity.sh
  manpages/pihole.8
  pihole
Labels: Documentation Needed, Enhancement, pr: Approved

#2271 Start changes to new code style for repository. Revise basic installer.sh spacing.
  .editorconfig
  .idea/codeStyles/Project.xml
  automated install/basic-install.sh
Labels: pr: Approved

#2262 additonal test coverage for installer
  .gitignore
  .travis.yml
  requirements.txt
  setup.py
  test/README.md
  test/conftest.py
  test/fedora.Dockerfile
  test/test_000_build_containers.py
  test/test_automated_install.py
  test/test_centos_fedora_support.py
  test/test_shellcheck.py
  tox.ini
Labels: pr: Approval Required

#2284 Added missing `.` for sourced file.
  automated install/basic-install.sh
Labels: Bug: fixed, pr: Approved

#2282 Updated port 53 check #2
  advanced/Scripts/COL_TABLE
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: pr: Approval Required, pr: Code Review Required

#2118 fix some shellcheck/stickler compaints in debug script
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required, pr: Code Review Required

#2287 Remove empty comment lines in basic-install.sh
  automated install/basic-install.sh
Labels: pr: Approved

#2297 Fixed locale issue, do not parse for string.
  automated install/basic-install.sh
Labels: pr: Approved

#2303 Update release/v4.0 with latest development changes
  advanced/Scripts/COL_TABLE
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: pr: Approval Required

#2304 Update FTLDNS with development
  advanced/Scripts/COL_TABLE
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: pr: Approval Required

#2307 Change the word "folder" to "directory" since the pi-hole is intended…
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: pr: Approval Required

#2311 Fix wrong git command flag
  automated install/basic-install.sh
Labels: Bug: fixed

#2312 Update FTLDNS
  automated install/basic-install.sh
Labels: pr: Approval Required

#2314 Fix FTL install leaking error output
  automated install/basic-install.sh
Labels: Bug: fixed, pr: Approved

#2310 Include template pihole-FTL.conf
  advanced/Templates/logrotate
  advanced/Templates/pihole-FTL.conf
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  advanced/Templates/pihole.sudo
  automated install/basic-install.sh
Labels: pr: Approved

#2313 Fix wildcard/regex usage formatting
  manpages/pihole.8
Labels: Bug: fixed, pr: Approval Required

#2315 Allow PHP to edit the regex file if web is installed
  automated install/basic-install.sh
  gravity.sh
Labels: Bug: fixed

#2317 Add empty pihole-FTL.conf file
  advanced/Templates/pihole-FTL.conf
  automated install/basic-install.sh
Labels: pr: Approval Required, pr: Code Review Required
