Repository pi-hole/pi-hole, pull requests merged in 2018-03, with the labels that each got.

#2016 Bugfix mktmp > mktemp
  automated install/basic-install.sh
Labels: pr: Approval Required, pr: Code Review Required

#2025 Disable dnsmasq FTLDNS
  automated install/basic-install.sh
  gravity.sh
  test/test_automated_install.py
Labels: pr: Approval Required, pr: Code Review Required

#2060 add label to x-header so you know which one is being evaluated
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required, pr: Code Review Required

#2054 Link to the admin panel on the splash page.
  advanced/index.php
Labels: pr: Approved

#1758 basic-install.sh - no CIDR in ifcfg-*
  automated install/basic-install.sh
Labels: In progress
