Repository pi-hole/pi-hole, pull requests merged in 2018-06, with the labels that each got.

#2214 Fix gravity_ParseFileIntoDomains Awk comment
  gravity.sh
Labels: pr: Approved

#2161 CentOS install re-worked to provide PHP7 via Remi Repository
  automated install/basic-install.sh
Labels: Documentation Needed, pr: Approved

#2219 Add coverage, remove projects, add Patreon link
  README.md
Labels: pr: Approval Required, pr: Code Review Required

#2004 Install 32bit FTL on 32bit OS (even if 64bit architecture is detected)
  automated install/basic-install.sh
Labels: Enhancement, Testing Required, pr: Approval Required, pr: Code Review Required

#2069 Fix error: /opt/pihole/gravity.sh: 385: Warning: command substitution: ignored null byte in input
  gravity.sh
Labels: Bug: fixed, WIP, pr: Code Review Required

#2246 Update debug script for simple list format
  advanced/Scripts/piholeDebug.sh
Labels: Bug: fixed

#2256 Fix incorrect variable string substitution
  advanced/Scripts/query.sh
Labels: Bug: fixed, pr: Approved
