Repository pi-hole/pi-hole, pull requests merged in 2019-05, with the labels that each got.

#2735 Fix incorrect adlist query when an adlist is blocked during gravity
  gravity.sh
Labels: Bug: fixed

#2738 Fix Untagged display on new installs
  automated install/basic-install.sh
Labels: Bug: fixed

#2744 Fix for preventing git error message in cron logs
  advanced/Scripts/updatecheck.sh
Labels: Bug: fixed

#2693 Pi-hole Core v4.3
  README.md
  advanced/Scripts/chronometer.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/Scripts/update.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/webpage.sh
  advanced/index.php
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  requirements.txt
Labels: Release

#2763 Handle an empty local.list
  gravity.sh
Labels: pr: Code Review Required

#2768 Add dhcp-ignore-names option when enabling DHCP service
  advanced/01-pihole.conf
  advanced/Scripts/webpage.sh
Labels: Bug: fixed
