Repository pi-hole/pi-hole, pull requests merged in 2019-08, with the labels that each got.

#2873 Simplify restarting code for "pihole restartdns"
  pihole
Labels: Bug: fixed

#2882 Fix error when getting latest FTL tag
  automated install/basic-install.sh
Labels: Bug: fixed, pr: Approved

#2886 Call 'pihole' with full path in install and cronjobs.
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  pihole
Labels: pr: Approval Required, pr: Code Review Required
