Repository pi-hole/pi-hole, pull requests merged in 2019-06, with the labels that each got.

#2767 Improve PID detection in pihole-FTL.service
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed

#2808 Fix uninstall causing 403 errors and not removing packages
  automated install/uninstall.sh
Labels: Bug: fixed

#2817 Add timeout to sqlite3 command
  gravity.sh
Labels: Enhancement

#2816 Fix lighttpd mime
  advanced/lighttpd.conf.debian
Labels: pr: Code Review Required

#2823 Update with v4.3.1 changes
  README.md
  advanced/lighttpd.conf.debian
Labels: Release
