Repository pi-hole/pi-hole, pull requests merged in 2019-01, with the labels that each got.

#2571 List content of /var/run/shm in debugger
  advanced/Scripts/piholeDebug.sh
Labels: Enhancement

#2581 remove unused dependency (bc)
  automated install/basic-install.sh
Labels: pr: Approved

#2601 Prevent double disabling/enabling
  pihole
Labels: Bug: fixed
