Repository pi-hole/pi-hole, pull requests merged in 2019-02, with the labels that each got.

#2602 Download FTL earlier in the installer
  automated install/basic-install.sh
  test/test_automated_install.py
Labels: Bug: fixed

#2610 Change /var/run/shm to /dev/shm
  advanced/Scripts/piholeDebug.sh
Labels: Bug: fixed

#2600 Release v4.2
  advanced/01-pihole.conf
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/version.sh
  advanced/Scripts/webpage.sh
  advanced/bash-completion/pihole
  automated install/basic-install.sh
  manpages/pihole-FTL.conf.5
  manpages/pihole.8
  pihole
  test/test_automated_install.py
Labels: Release

#2614 Merge v4.2.1 hotfix to dev
  advanced/01-pihole.conf
Labels: Release

#2612 Remove user/group from dnsmasq config
  advanced/01-pihole.conf
Labels: Release

#2626 Pi-hole Core v4.2.2
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed, Release

#2639 Update development from hotfix/v4.2.2
  advanced/Templates/pihole-FTL.service
Labels: Release

#2647 Use `curl` instead of `openssl` for debug upload.
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approved
