Repository pi-hole/pi-hole, pull requests merged in 2019-12, with the labels that each got.

#3024 Get binary name in update.sh
  advanced/Scripts/update.sh
Labels: Bug: fixed

#3030 Ensure database permissions are set up correctly by the service script
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed, Enhancement

#3031 Do not force nameserver 127.0.0.1 through resolvconf
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed

#2935 Per-client blocking changes
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/3_to_4.sql
  advanced/Scripts/database_migration/gravity/4_to_5.sql
  advanced/Scripts/database_migration/gravity/5_to_6.sql
  gravity.sh
Labels: Enhancement

#3036 Improve list reloading
  advanced/Scripts/list.sh
  pihole
Labels: Enhancement

#3034 Show full URL during gravity download
  gravity.sh
Labels: Enhancement

#3033 Remove duplicates from adlists before importing
  gravity.sh
Labels: Bug: fixed

#3035 pihole -q should also scan gravity table
  advanced/Scripts/query.sh
Labels: Bug: fixed

#3037 Add special group zero to gravity database
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/6_to_7.sql
Labels: Enhancement

#3052 Revert "Change the regex used for domain validation"
  advanced/Scripts/list.sh
Labels: Bug: fixed

#3045 Set permissions and ownership of gravity.db on pihole -g
  gravity.sh
Labels: Enhancement

#3049 Group table enhancements
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/7_to_8.sql
Labels: Enhancement
