Repository pi-hole/pi-hole, pull requests merged in 2019-09, with the labels that each got.

#2838 Whitelist regex support
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/1_to_2.sql
  advanced/Scripts/database_migration/gravity/2_to_3.sql
  advanced/Scripts/list.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  automated install/basic-install.sh
  gravity.sh
  manpages/pihole.8
  pihole
Labels: Feature Request: Discourse

#2903 Store timestamp when the gravity table was last updated successfully
  gravity.sh
Labels: Bug: fixed, pr: Approval Required

#2909 Print messages only after removing possible matches in comments
  advanced/Scripts/query.sh
Labels: Bug: fixed, pr: Approval Required

#2915 Prevent Firefox from automatically switching over to DNS-over-HTTPS
  advanced/01-pihole.conf
Labels: Feature Request: Discourse

#2881 Pi-hole Core v4.3.2
  .github/FUNDING.yml
  advanced/01-pihole.conf
  advanced/Scripts/query.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/pihole-FTL.service
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  manpages/pihole.8
  pihole
  test/fedora.Dockerfile
  test/test_automated_install.py
Labels: Documentation Needed, Release, pr: Approval Required, pr: Code Review Required
