Repository pi-hole/pi-hole, pull requests merged in 2019-03, with the labels that each got.

#2659 Warn user during update if FTL is on a custom branch
  advanced/Scripts/update.sh
Labels: Enhancement

#2637 Support pi hole behind a reverse proxy with ssl
  advanced/index.php
Labels: pr: Code Review Required

#2646 Don't fail when trying to detect OS architecture on RPM-based systems
  automated install/basic-install.sh
Labels: Bug: fixed

#2688 Add Check to `pihole -q -exact` to ensure there is no `#` char preceding a space before the domain
  advanced/Scripts/query.sh
Labels: Bug: fixed
