Repository pi-hole/pi-hole, pull requests merged in 2020-05, with the labels that each got.

#3318 Rename default group to ... well ... "Default"
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/11_to_12.sql
  advanced/Templates/gravity.db.sql
Labels: Enhancement

#3321 Pi-hole core v5.0
  .github/FUNDING.yml
  README.md
  advanced/01-pihole.conf
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/10_to_11.sql
  advanced/Scripts/database_migration/gravity/11_to_12.sql
  advanced/Scripts/database_migration/gravity/1_to_2.sql
  advanced/Scripts/database_migration/gravity/2_to_3.sql
  advanced/Scripts/database_migration/gravity/3_to_4.sql
  advanced/Scripts/database_migration/gravity/4_to_5.sql
  advanced/Scripts/database_migration/gravity/5_to_6.sql
  advanced/Scripts/database_migration/gravity/6_to_7.sql
  advanced/Scripts/database_migration/gravity/7_to_8.sql
  advanced/Scripts/database_migration/gravity/8_to_9.sql
  advanced/Scripts/database_migration/gravity/9_to_10.sql
  advanced/Scripts/list.sh
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/query.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/version.sh
  advanced/Scripts/webpage.sh
  advanced/Scripts/wildcard_regex_converter.sh
  advanced/Templates/gravity.db.sql
  advanced/Templates/gravity_copy.sql
  advanced/Templates/pihole-FTL.service
  advanced/bash-completion/pihole
  advanced/index.php
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  manpages/pihole.8
  pihole
  test/test_automated_install.py
  test/test_centos_fedora_support.py
Labels: Release

#3327 Implement backend support for theming
  advanced/Scripts/webpage.sh
Labels: Enhancement, Feature Request: Discourse

#3369 Remove store/shop link from README
  README.md
Labels: PR: Master branch

#3455 Add CAP_SYS_NICE to FTL's capabilities
  advanced/Templates/pihole-FTL.service
Labels: Enhancement
