Repository pi-hole/pi-hole, pull requests merged in 2020-10, with the labels that each got.

#3741 Discover active DHCP servers during debugger run
  advanced/Scripts/piholeDebug.sh
Labels: Enhancement

#3740 Add date_updated field to adlist table
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/12_to_13.sql
  advanced/Templates/gravity.db.sql
  gravity.sh
Labels: Bug: fixed

#3225 web server question enhancements
  automated install/basic-install.sh
Labels: Merge Conflict

#3801 Add native ARMv4T, ARMv5TE and ARMv8-A support
  automated install/basic-install.sh
  test/test_automated_install.py
Labels: Feature Request: Discourse, pr: Approval Required

#3794 Security enhancement for the "never forward non-FQDNs" feature
  advanced/Scripts/webpage.sh
Labels: Security
