Repository pi-hole/pi-hole, pull requests merged in 2020-04, with the labels that each got.

#3242 Do not flush neigh cache
  advanced/Scripts/piholeARPTable.sh
Labels: Bug: fixed, pr: Approval Required

#3259 Update development from release/v5.0
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  gravity.sh
Labels: pr: Approval Required

#3269 Add support for comments in HOSTS-like files
  gravity.sh
Labels: Bug: fixed, Enhancement

#3252 add [options] for 'pihole restart' to manpage and cli help output
  manpages/pihole.8
  pihole
Labels: Enhancement

#3227 Add option --comment "whatever" for adding comments for new domains through the CLI interface.
  advanced/Scripts/list.sh
Labels: Enhancement, Feature Request: Discourse

#3289 Gravity: Boldify number of unique domains
  gravity.sh
Labels: Enhancement

#3296 Remove pihole -a hostrecord
  advanced/Scripts/webpage.sh
  advanced/bash-completion/pihole
  manpages/pihole.8
Labels: Feature Request

#3299 Allow ( and ) in adlist URLs.
  gravity.sh
Labels: Enhancement

#3307 Improve debugger database table printing
  advanced/Scripts/piholeDebug.sh
Labels: Enhancement
