Repository pi-hole/pi-hole, pull requests merged in 2020-11, with the labels that each got.

#3810 Enable DNS forwarding loop detection
  advanced/01-pihole.conf
Labels: Documentation Needed, pr: Approved

#3761 read REV_SERVER_CIDR from environment
  advanced/Scripts/webpage.sh
Labels: Documentation Needed, pr: Approved

#3849 -remove duplicate OS dockerfiles
  .stickler.yml
  test/centos_7.Dockerfile
  test/centos_8.Dockerfile
  test/conftest.py
  test/debian.Dockerfile
  test/fedora.Dockerfile
  test/test_centos_fedora_support.py
  tox.ini
Labels: pr: Approved

#3851 Include secondary upstream DNS for Quad9+Filter+ECS
  automated install/basic-install.sh
Labels: pr: Approved

#3854 Nothing to see here. I just forgot a page.
  test/test_000_build_containers.py
Labels: pr: Approved

#3862 Include the raw messages from the Pi-hole diagnosis systems in debug logs
  advanced/Scripts/piholeDebug.sh
Labels: Debugging, pr: Approval Required

#3874 Don't delete entries including and greater than `PIHOLE_DNS_10` on update/repair
  automated install/basic-install.sh
Labels: Bug: fixed, pr: Approval Required, pr: Code Review Required
