Repository pi-hole/pi-hole, pull requests merged in 2020-12, with the labels that each got.

#3887 Fix "Never forward non-FQDNs" checkbox
  advanced/Scripts/webpage.sh
Labels: Bug: fixed

#3882 Fix processing of CONDITIONAL_FORWARDING_REVERSE
  advanced/Scripts/webpage.sh
Labels: pr: Approval Required, pr: Code Review Required

#3892 Fix debugger stripping content it shouldn't
  advanced/Scripts/piholeDebug.sh
Labels: Bug: fixed

#3889 Pi-hole Core release v5.2.1
  .github/workflows/test.yml
  .travis.yml
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  autotest
  test/_centos_7.Dockerfile
  test/_centos_8.Dockerfile
  test/_debian_10.Dockerfile
  test/_debian_9.Dockerfile
  test/_fedora_31.Dockerfile
  test/_fedora_32.Dockerfile
  test/_ubuntu_16.Dockerfile
  test/_ubuntu_18.Dockerfile
  test/_ubuntu_20.Dockerfile
  test/conftest.py
  test/requirements.txt
  test/setup.py
  test/test_000_build_containers.py
  test/test_centos_7_support.py
  test/test_centos_8_support.py
  test/test_centos_common_support.py
  test/test_centos_fedora_common_support.py
  test/test_centos_fedora_support.py
  test/test_fedora_support.py
  test/test_shellcheck.py
  test/tox.centos_7.ini
  test/tox.centos_8.ini
  test/tox.debian_10.ini
  test/tox.debian_9.ini
  test/tox.fedora_31.ini
  test/tox.fedora_32.ini
  test/tox.ubuntu_16.ini
  test/tox.ubuntu_18.ini
  test/tox.ubuntu_20.ini
  tox.ini
Labels: Release, pr: Approval Required

#3909 Adding comma to the adlist table format
  gravity.sh
Labels: Bug: fixed

#3934 Fix typo found by #3933
  advanced/Templates/gravity.db.sql
Labels: pr: Approval Required, pr: Code Review Required

#3954 Fix connection mechanism between Chronometer and FTL
  advanced/Scripts/chronometer.sh
Labels: Bug: fixed
