Repository pi-hole/pi-hole, pull requests merged in 2020-07, with the labels that each got.

#2887 Prevent "pihole disable $timeout" from messing up future state changes
  advanced/Scripts/pihole-reenable.sh
  pihole
Labels: Merge Conflict

#3531 Pi-hole Core v5.1
  .editorconfig
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .stickler.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  advanced/Scripts/COL_TABLE
  advanced/Scripts/chronometer.sh
  advanced/Scripts/pihole-reenable.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/Scripts/setupLCD.sh
  advanced/Scripts/version.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/gravity.db.sql
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  advanced/blockingpage.css
  advanced/dnsmasq.conf.original
  advanced/index.php
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  automated install/uninstall.sh
  block hulu ads/lighttpd.conf
  block hulu ads/minidlna.conf
  gravity.sh
  manpages/pihole.8
  pihole
  supportedos.txt
  test/README.md
  test/conftest.py
  test/test_000_build_containers.py
  test/test_automated_install.py
  test/test_centos_fedora_support.py
  test/test_shellcheck.py
  tox.ini
Labels: Release

#3599 Fix for gravity cronjob
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  gravity.sh
  pihole
Labels: Bug: fixed

#3524 Fix pihole status to not rely on a TCP port test
  pihole
Labels: Bug: fixed
