Repository pi-hole/pi-hole, pull requests merged in 2020-06, with the labels that each got.

#3466 Allow certain domain duplicates
  advanced/Templates/gravity.db.sql
Labels: Enhancement

#3470 Replace possible "\#" by "#" to fix AdminLTE#1427
  advanced/Scripts/webpage.sh
Labels: Bug: fixed

#3490 Fix new os_check
  automated install/basic-install.sh
Labels: Bug: fixed, Priority: High

#3492 Improve man pihole restartdns section
  manpages/pihole.8
Labels: Documented, Enhancement

#3489 Improve IP validation function
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
Labels: Enhancement, Security

#3491 Fix fresh install on dev branch not working
  advanced/Scripts/piholeDebug.sh
  automated install/basic-install.sh
Labels: Bug: fixed, Priority: High

#3260 Improve conditional forwarding
  advanced/Scripts/webpage.sh
Labels: Enhancement
