Repository pi-hole/pi-hole, pull requests merged in 2020-02, with the labels that each got.

#3115 Store number of distinct gravity domains in database after counting
  gravity.sh
Labels: Enhancement

#3106 DROP and reCREATE TRIGGERs during gravity swapping.
  advanced/Templates/gravity_copy.sql
Labels: Bug: fixed

#3107 Add timestamps and comment fields to clients table
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/10_to_11.sql
  advanced/Templates/gravity.db.sql
Labels: Enhancement

#3138 Install php-intl meta package.
  automated install/basic-install.sh
Labels: Bug: fixed

#3130 Store gravity update timestamp only after database swapping
  gravity.sh
Labels: Bug: fixed

#3139 Fix wrong number of blocking domains shown on the dashboard
  gravity.sh
Labels: Bug: fixed

#3132 Fix pihole -t sed instructions
  pihole
Labels: Bug: fixed

#3144 Fix issue with missing newline at the end of adlists
  gravity.sh
Labels: Bug: fixed

#3150 Gravity: Check suitablility of sourced lists
  gravity.sh
Labels: Enhancement

#3152 Update development with latest release/v5.0 changes
  .github/FUNDING.yml
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/10_to_11.sql
  advanced/Scripts/database_migration/gravity/9_to_10.sql
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/update.sh
  advanced/Templates/gravity.db.sql
  advanced/Templates/gravity_copy.sql
  advanced/index.php
  automated install/basic-install.sh
  gravity.sh
  pihole
Labels: Internal
