Repository pi-hole/pi-hole, pull requests merged in 2021-09, with the labels that each got.

#4317 Forward unqualified names to the CF target only when the "Never forward non-FQDN" option is NOT ticked
  advanced/Scripts/webpage.sh
Labels: Bug: fixed, beta

#4314 Add possibly missing capabilities
  advanced/Templates/pihole-FTL.service
Labels: Bug: fixed

#4282 Install RFC6761 config file
  advanced/06-rfc6761.conf
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: Nice to have, Feature Request: Discourse

#4243 Include all files in the dnsmasq config dir in the debug output
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required, Debugging
