Repository pi-hole/pi-hole, pull requests merged in 2021-08, with the labels that each got.

#4248 Fix error on checking interfaces that are not dual-stack
  advanced/Scripts/piholeDebug.sh
Labels: Debugging

#4246 Remove comparison of IP addresses with setupVars.conf
  advanced/Scripts/piholeDebug.sh
Labels: Bug: fixed

#4264 On enabling/disabeling only reload-lists instead of reload
  pihole
Labels: pr: Approved

#4287 Conditional forwarding: Also forward unqualified host names
  advanced/Scripts/webpage.sh
Labels: Bug: fixed

#4304 Fix pipe to pihole tricorder
  advanced/Scripts/piholeDebug.sh
  pihole
Labels: Bug: fixed, beta
