Repository pi-hole/pi-hole, pull requests merged in 2021-01, with the labels that each got.

#3537 Further failsafe check for available APT packages
  automated install/basic-install.sh
Labels: Enhancement, pr: Approval Required, pr: Code Review Required

#3987 Use the 'Location:' header only for latest FTL tag API check.
  automated install/basic-install.sh
Labels: pr: Approved, pr: Code Review Required

#3989 Pi-hole Core v5.2.3
  advanced/Scripts/chronometer.sh
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  gravity.sh
Labels: Release, pr: Approval Required
