Repository pi-hole/pi-hole, pull requests merged in 2021-12, with the labels that each got.

#4445 Fix number of invalid domains
  gravity.sh
Labels: pr: Approval Required

#4478 Gravity database handling improvements
  gravity.sh
Labels: pr: Code Review Required, pr: Approval Required

#4476 Add new interface listening option "bind"
  advanced/Scripts/webpage.sh
Labels: Enhancement

#4461 Companion to pi-hole/adminlte #1996
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
Labels: pr: Approval Required

#4414 Add custom.list (Local DNS Records) to debug log
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approved

#4433 Replace Contributing Guide by link to docs.pi-hole.net
  CONTRIBUTING.md
Labels: pr: Approval Required

#4450 Unblock adlist domain during gravity run in NODATA mode
  gravity.sh
Labels: pr: Approval Required

#4455 Add comment help text to list function
  advanced/Scripts/list.sh
Labels: pr: Approval Required

#4475 Check for updates on master based on tags not commits
  advanced/Scripts/update.sh
Labels: pr: Code Review Required

#4288 Implement fully-automated gravity database recovery method
  gravity.sh
Labels: pr: Approval Required

#4480 Pi-hole Core v5.7
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  advanced/06-rfc6761.conf
  advanced/Scripts/chronometer.sh
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/list.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/Scripts/update.sh
  advanced/Scripts/version.sh
  advanced/Scripts/webpage.sh
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  gravity.sh
  pihole
  test/README.md
  test/_centos_7.Dockerfile
  test/_centos_8.Dockerfile
  test/_fedora_33.Dockerfile
  test/_fedora_34.Dockerfile
  test/conftest.py
  test/requirements.txt
  test/test_automated_install.py
  test/test_centos_7_support.py
  test/test_centos_8_support.py
  test/test_centos_common_support.py
  test/test_centos_fedora_common_support.py
  test/test_fedora_support.py
  test/tox.centos_7.ini
  test/tox.centos_8.ini
  test/tox.debian_10.ini
  test/tox.debian_11.ini
  test/tox.debian_9.ini
  test/tox.fedora_33.ini
  test/tox.fedora_34.ini
  test/tox.ubuntu_16.ini
  test/tox.ubuntu_18.ini
  test/tox.ubuntu_20.ini
  test/tox.ubuntu_21.ini
Labels: Release

#4485 Return the port FTL is listening on in pihole status function
  automated install/basic-install.sh
  pihole
Labels: pr: Code Review Required
