Repository pi-hole/pi-hole, pull requests merged in 2021-04, with the labels that each got.

#4086 pihole -g should respose GRAVITYDB in pihole-FTL.conf
  advanced/Scripts/list.sh
  advanced/Scripts/query.sh
  gravity.sh
Labels: Bug: fixed, pr: Approved

#4083 Improve regexes for IPv4 matching
  automated install/basic-install.sh
  test/test_automated_install.py
Labels: Merge Conflict

#4103 Obtain FTL's PID from the PID file
  pihole
Labels: Enhancement, pr: Approved

#4117 v5.8 master to dev
  .github/workflows/test.yml
  README.md
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  pihole
  supportedos.txt
  test/_fedora_33.Dockerfile
  test/tox.fedora_33.ini
Labels: Internal

#4121 Fix port separator in IPv4 address validation code
  automated install/basic-install.sh
  test/test_automated_install.py
Labels: Bug: fixed
