Repository pi-hole/pi-hole, pull requests merged in 2022-08, with the labels that each got.

#4833 Explicit set minor and patch version on used actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
Labels: internal, pr: Approved

#4851 Dont use bash keywords/programs as variable names
  advanced/Scripts/query.sh
  gravity.sh
Labels: internal

#4855 Ensure user defined FTL_PID_FILE and FTL_PORT_FILE dirs are created on startup
  advanced/Templates/pihole-FTL.service
Labels: pr: Approval Required

#4857 Exit init script with error result code if FTL fails to start
  advanced/Templates/pihole-FTL.service
Labels: pr: Approval Required, Bug: fixed

#4863 Fix git indention
  automated install/basic-install.sh
Labels: pr: Approval Required

#4864 Extend FTL information in debug log
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required

#3910 Remove the advanced functionality of the 404 page (Blockpage)
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/blockingpage.css
  advanced/index.php
  automated install/basic-install.sh
  test/test_any_automated_install.py
Labels: pr: Code Review Required

#4862 Add security-related headers to Pi-hole web interface
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
Labels: Security, pr: Approval Required

#4878 Add jq as dependency and remove json_extract
  advanced/Scripts/updatecheck.sh
  automated install/basic-install.sh
Labels: pr: Approval Required
