Repository pi-hole/pi-hole, pull requests merged in 2022-09, with the labels that each got.

#4889 Release 5.12
  .github/workflows/codeql-analysis.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
  README.md
  advanced/GIFs/25Bytes.gif
  advanced/GIFs/26Bytes.gif
  advanced/GIFs/37Bytes.gif
  advanced/GIFs/43Bytes.gif
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/Scripts/setupLCD.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/utils.sh
  advanced/Scripts/version.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/pihole-FTL.service
  advanced/bash-completion/pihole
  advanced/blockingpage.css
  advanced/cmdline.txt
  advanced/console-setup
  advanced/index.php
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  manpages/pihole.8
  pihole
  test/_centos_7.Dockerfile
  test/_ubuntu_21.Dockerfile
  test/centos7.epel.override
  test/test_any_automated_install.py
  test/test_any_utils.py
  test/test_centos_7_support.py
  test/test_centos_8_support.py
  test/test_centos_common_support.py
  test/test_fedora_support.py
  test/tox.centos_7.ini
  test/tox.centos_8.ini
  test/tox.ubuntu_21.ini
Labels: Release, pr: Approved

#4899 Fix 4898
  pihole
Labels: pr: Approval Required

#4908 v5.12.1
  .github/workflows/test.yml
  pihole
  test/_ubuntu_18.Dockerfile
  test/test_any_automated_install.py
  test/tox.ubuntu_18.ini
Labels: internal

#4917 Add comment in lighttpd.conf how to change the server port
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
Labels: pr: Approval Required

#4914 Update workflow python to 3.10 and allow any python3 version in tests
  .github/workflows/test.yml
  test/setup.py
  test/tox.centos_8.ini
  test/tox.debian_10.ini
  test/tox.debian_11.ini
  test/tox.fedora_34.ini
  test/tox.ubuntu_20.ini
  test/tox.ubuntu_22.ini
Labels: pr: Approval Required, internal

#4921 Fix gravity database integrity check
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required

#4932 Fix tabs in dialog boxes
  automated install/basic-install.sh
Labels: pr: Approval Required

#4910 Change wording in chronometer
  advanced/Scripts/chronometer.sh
Labels: pr: Approval Required, Feature Request: Discourse

#4872 Use utils.sh in install script
  advanced/01-pihole.conf
  automated install/basic-install.sh
  test/test_any_automated_install.py
Labels: pr: Code Review Required

#4884 Set connection timeout for curl
  gravity.sh
Labels: Feature Request, Discussion, pr: Approved

#4929 Read docker tag from file in root, not the previously set environment variable
  advanced/Scripts/updatecheck.sh
Labels: pr: Approved

#4934 Handle more than one default gateway in debug script
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approved
