Repository pi-hole/pi-hole, pull requests merged in 2022-07, with the labels that each got.

#4773 Add mkdown and yaml linters to stickler
  .stickler.yml
Labels: pr: Approval Required, internal

#4771 Action/editorconfig checker
  .editorconfig
  .github/workflows/editorconfig-checker.yml
  CONTRIBUTING.md
  advanced/Scripts/database_migration/gravity/11_to_12.sql
  advanced/Scripts/database_migration/gravity/12_to_13.sql
  advanced/Scripts/database_migration/gravity/3_to_4.sql
  advanced/Scripts/database_migration/gravity/4_to_5.sql
  advanced/Scripts/utils.sh
Labels: pr: Approval Required, internal

#4713 Add code-spell action / Move editorconfig-checker action to smoke-tests
  .codespellignore
  .github/workflows/editorconfig-checker.yml
  .github/workflows/test.yml
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/webpage.sh
  advanced/dnsmasq.conf.original
  automated install/basic-install.sh
  gravity.sh
  test/test_any_automated_install.py
Labels: internal

#4776 Run stale workflow at 8:00 once per day
  .github/workflows/stale.yml
Labels: pr: Approval Required

#4782 Fix close-issue-reason
  .github/workflows/stale.yml
Labels: pr: Approval Required

#4790 [Meta] Reformat yml files
  .github/workflows/stale.yml
  .stickler.yml
  .yamllint.conf
Labels: internal, pr: Approved

#4789 v5.11 Release
  .codespellignore
  .editorconfig
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
  .stickler.yml
  .yamllint.conf
  CONTRIBUTING.md
  advanced/01-pihole.conf
  advanced/Scripts/database_migration/gravity/11_to_12.sql
  advanced/Scripts/database_migration/gravity/12_to_13.sql
  advanced/Scripts/database_migration/gravity/3_to_4.sql
  advanced/Scripts/database_migration/gravity/4_to_5.sql
  advanced/Scripts/list.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/utils.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/logrotate
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  advanced/dnsmasq.conf.original
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  manpages/pihole.8
  pihole
  test/_centos_7.Dockerfile
  test/_debian_9.Dockerfile
  test/_ubuntu_16.Dockerfile
  test/_ubuntu_22.Dockerfile
  test/centos7.epel.override
  test/test_any_automated_install.py
  test/test_centos_7_support.py
  test/test_centos_8_support.py
  test/test_centos_common_support.py
  test/tox.fedora_33.ini
  test/tox.ubuntu_16.ini
  test/tox.ubuntu_22.ini
Labels: internal

#4804 Clean consecutive mkdir
  automated install/basic-install.sh
Labels: pr: Approval Required

#4788 Rename PH_TEST to SKIP_INSTALL
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/update.sh
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  automated install/uninstall.sh
  test/_centos_7.Dockerfile
  test/_centos_8.Dockerfile
  test/_debian_10.Dockerfile
  test/_debian_11.Dockerfile
  test/_fedora_34.Dockerfile
  test/_ubuntu_18.Dockerfile
  test/_ubuntu_20.Dockerfile
  test/_ubuntu_21.Dockerfile
  test/_ubuntu_22.Dockerfile
Labels: pr: Approval Required

#4810 Fix broken logrotate config by updating old paths in existing file if they exist
  automated install/basic-install.sh
Labels: pr: Approval Required

#4811 Print all SELINUX output in lowercase
  automated install/basic-install.sh
  test/test_centos_fedora_common_support.py
Labels: pr: Approval Required

#4812 Pi-hole core 5.11.4
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/setupLCD.sh
  advanced/Scripts/update.sh
  advanced/Scripts/webpage.sh
  automated install/basic-install.sh
  automated install/uninstall.sh
  test/_centos_7.Dockerfile
  test/_centos_8.Dockerfile
  test/_debian_10.Dockerfile
  test/_debian_11.Dockerfile
  test/_fedora_34.Dockerfile
  test/_ubuntu_18.Dockerfile
  test/_ubuntu_20.Dockerfile
  test/_ubuntu_21.Dockerfile
  test/_ubuntu_22.Dockerfile
  test/test_centos_fedora_common_support.py
Labels: internal

#4745 Add optional health check to Pi-hole databases in debug script
  advanced/Scripts/piholeDebug.sh
  gravity.sh
  pihole
Labels: pr: Approval Required

#4825 Fix shellcheck warnings
  automated install/basic-install.sh
Labels: pr: Approved

#4824 Don't fail if Alma or Rocky are detected
  automated install/basic-install.sh
Labels: Discussion, pr: Approved

#4837 Dont fail fast on tests
  .github/workflows/test.yml
  test/_ubuntu_21.Dockerfile
  test/tox.ubuntu_21.ini
Labels: internal

#4838 Use prefers-color-scheme for theme based logo
  README.md
Labels: pr: Approval Required

#4832 Fix spaces in dialog msg
  automated install/basic-install.sh
Labels: pr: Approval Required

#4846 Add OS_CHECK_DEPS to uninstall script
  automated install/uninstall.sh
Labels: pr: Approval Required

#4848 Indent installation/update complete message
  automated install/basic-install.sh
Labels: pr: Approval Required

#4847 Remove unused and outdated files and scripts
  advanced/GIFs/25Bytes.gif
  advanced/GIFs/26Bytes.gif
  advanced/GIFs/37Bytes.gif
  advanced/GIFs/43Bytes.gif
  advanced/Scripts/setupLCD.sh
  advanced/cmdline.txt
  advanced/console-setup
Labels: Discussion

#4839 Move FTL port and PID functions to utils.sh
  advanced/Scripts/utils.sh
  advanced/Templates/pihole-FTL.service
  pihole
  test/test_any_utils.py
Labels: pr: Code Review Required

#4828 Drop explicit support for CentOS 7 from the install script
  .github/workflows/test.yml
  automated install/basic-install.sh
  test/_centos_7.Dockerfile
  test/centos7.epel.override
  test/test_any_automated_install.py
  test/test_centos_7_support.py
  test/test_centos_8_support.py
  test/test_centos_common_support.py
  test/test_fedora_support.py
  test/tox.centos_7.ini
  test/tox.centos_8.ini
Labels: Documentation Needed
