Repository pi-hole/pi-hole, pull requests merged in 2022-01, with the labels that each got.

#4509 Set dnsmasq interface listening by default to local
  automated install/basic-install.sh
Labels: pr: Approval Required

#4494 Skip debug upload question if called from web interface
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required

#4496 Install pihole-FTL.conf template on fresh installation
  advanced/Templates/pihole-FTL.conf
  automated install/basic-install.sh
Labels: pr: Code Review Required

#4518 Use ss instead of lsof
  advanced/Scripts/piholeDebug.sh
  automated install/basic-install.sh
  pihole
Labels: Bug: fixed

#4521 Fix/chronometer
  advanced/Scripts/chronometer.sh
Labels: pr: Approval Required

#4534 Enable Stale Action for live use
  .github/workflows/stale.yml
Labels: Internal

#4535 Fix gravity in case there are no adlists at all or all are disabled
  gravity.sh
Labels: Bug: fixed

#4532 Install netcat-openbsd as dependency explicitly
  automated install/basic-install.sh
Labels: pr: Approved

#4542 Remove oneline from ss call
  advanced/Scripts/piholeDebug.sh
Labels: pr: Code Review Required

#4543 Include ip addr show and ip route show in debug log
  advanced/Scripts/piholeDebug.sh
Labels: Debugging

#4548 [Maintenance] Sync Master back to Dev when code is pushed to master
  .github/release.yml
  .github/workflows/sync-back-to-dev.yml
Labels: Internal

#4558 Change the exemption issue label pinned to internal for stale issues
  .github/workflows/stale.yml
Labels: Internal
