Repository pi-hole/pi-hole, pull requests merged in 2022-11, with the labels that each got.

#4959 Simplify versions.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/update.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/version.sh
  advanced/Templates/pihole.cron
  automated install/basic-install.sh
Labels: Testing Required, pr: Code Review Required

#4999 Touch files before addKey or addOrEditKeyValPair
  advanced/Scripts/utils.sh
Labels: pr: Approval Required

#4907 Replace deprecated shell commands
  automated install/basic-install.sh
  test/test_any_automated_install.py
Labels: pr: Approval Required

#5012 Pi-hole core v5.14
  .github/workflows/test.yml
  README.md
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/update.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/utils.sh
  advanced/Scripts/version.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/pihole.cron
  automated install/basic-install.sh
  gravity.sh
  test/_centos_9.Dockerfile
  test/test_any_automated_install.py
  test/tox.centos_9.ini
Labels: Release, internal

#5028 Don't install `which`
  automated install/basic-install.sh
Labels: pr: Approved

#5035 Fix pihole updatecheck reboot
  pihole
Labels: pr: Approved

#5040 v5.14.2
  advanced/Scripts/updatecheck.sh
  automated install/basic-install.sh
  pihole
Labels: internal

#5037 Do not require man pages to be present in test script
  test/test_any_automated_install.py
Labels: pr: Approval Required
