Repository pi-hole/pi-hole, pull requests merged in 2022-10, with the labels that each got.

#4945 Remove pihole-FTL.port file
  advanced/Scripts/chronometer.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/utils.sh
  advanced/Templates/pihole-FTL.service
  pihole
  test/test_any_utils.py
Labels: pr: Approval Required

#4952 Add Fedora 35 and 36 to the test suite
  .github/workflows/test.yml
  test/_fedora_35.Dockerfile
  test/_fedora_36.Dockerfile
  test/tox.fedora_35.ini
  test/tox.fedora_36.ini
Labels: pr: Approved

#4966 Add initscripts to CentOS8 dockerfile
  test/_centos_8.Dockerfile
Labels: pr: Approval Required, internal

#4818 Fix errors in README.md
  README.md
Labels: Submitter Attention Required, internal

#4980 Bump actions/setup-python from 4.2.0 to 4.3.0
  .github/workflows/test.yml
Labels: internal

#4990 Escape dots in local DNS records/CNAMES before removing them
  advanced/Scripts/webpage.sh
Labels: Bug: fixed, pr: Approved

#4974 Remove unused possibility to obfuscate pihole.log in debug log
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approval Required

#4973 Remove check for latest component version in debug log
  advanced/Scripts/piholeDebug.sh
Labels: pr: Approved

#4988 Prevent CNAME loop
  advanced/Scripts/webpage.sh
Labels: pr: Approval Required
