Repository pi-hole/pi-hole, pull requests merged in 2022-02, with the labels that each got.

#4584 Replace calls to sqlite3 by calls to pihole-FTL sqlite3
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/list.sh
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/query.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/gravity_copy.sql
  automated install/basic-install.sh
  gravity.sh
Labels: Enhancement, Bug: fixed

#4489 Remove pihole-FTL.conf manpage
  automated install/basic-install.sh
  manpages/pihole-FTL.8
  manpages/pihole-FTL.conf.5
  test/test_any_automated_install.py
Labels: pr: Approved

#4547 Pi-hole Core v5.9
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/list.sh
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/query.sh
  advanced/Scripts/update.sh
  advanced/Scripts/utils.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/gravity_copy.sql
  automated install/basic-install.sh
  gravity.sh
  manpages/pihole-FTL.8
  manpages/pihole-FTL.conf.5
  pihole
  test/_centos_8.Dockerfile
  test/test_any_automated_install.py
  test/test_any_utils.py
  test/tox.centos_7.ini
  test/tox.centos_8.ini
  test/tox.debian_10.ini
  test/tox.debian_11.ini
  test/tox.debian_9.ini
  test/tox.fedora_33.ini
  test/tox.fedora_34.ini
  test/tox.ubuntu_16.ini
  test/tox.ubuntu_18.ini
  test/tox.ubuntu_20.ini
  test/tox.ubuntu_21.ini
Labels: Release, internal
