Repository pi-hole/pi-hole, pull requests merged in 2022-06, with the labels that each got.

#4356 Remove IPv4 and IPv6 adresses from setupVars.conf
  automated install/basic-install.sh
  test/test_any_automated_install.py
Labels: pr: Approval Required

#4756 Update dependabot.yml
  .github/dependabot.yml
Labels: internal

#4757 Exit installer if no valid PHP version is found
  automated install/basic-install.sh
Labels: pr: Approved

#4769 Remove unnecessary file types from editorconfig
  .editorconfig
Labels: internal

#4761 Require sudo for pihole -t
  pihole
Labels: pr: Approved

#4767 Add stale-issue-reason: not planned
  .github/workflows/stale.yml
Labels: internal, PR: Master branch

#4760 Remove read permission for others on sensible log files
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Templates/pihole-FTL.service
Labels: pr: Approved

#4762 Update test to reflect currently supported OS
  .github/workflows/test.yml
  advanced/Scripts/piholeDebug.sh
  test/_debian_9.Dockerfile
  test/_ubuntu_16.Dockerfile
  test/_ubuntu_22.Dockerfile
  test/tox.fedora_33.ini
  test/tox.ubuntu_16.ini
  test/tox.ubuntu_22.ini
Labels: Discussion, pr: Approval Required, internal
