Repository pi-hole/pi-hole, pull requests merged in 2022-05, with the labels that each got.

#4680 Respect user configurable path for pid and port file in pihole-FTL.service
  advanced/Templates/pihole-FTL.service
Labels: pr: Code Review Required

#4729 Typo fix on dependabot yaml.
  .github/dependabot.yml
Labels: internal, Meta

#4735 Logo for light and dark modes.
  README.md
Labels: internal, Meta

#4738 Always install pihole-FTL.service file
  automated install/basic-install.sh
Labels: pr: Approved

#4747 Change lighttpd log file names
  advanced/Scripts/piholeDebug.sh
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
Labels: pr: Approved

#4749 Do not hardcode webroot dir for teleporter
  advanced/Scripts/webpage.sh
Labels: pr: Approved

#3732 Utilise /var/log/pihole/ for log storage
  advanced/01-pihole.conf
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Templates/logrotate
  advanced/Templates/pihole-FTL.service
  advanced/Templates/pihole.cron
  automated install/basic-install.sh
  automated install/uninstall.sh
  manpages/pihole.8
  pihole
  test/test_any_automated_install.py
Labels: pr: Approved
