Repository pi-hole/pi-hole, pull requests merged in 2023-02, with the labels that each got.

#5157 Only source versions file if the file exits
  pihole
Labels: PR: Approved

#5144 Add pihole-admin.conf to debug log
  advanced/Scripts/piholeDebug.sh
Labels: PR: Approved

#5165 Pi-hole core v5.15.4
  advanced/Scripts/piholeDebug.sh
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  automated install/basic-install.sh
  pihole
  test/requirements.txt
Labels: Release, internal

#5176 Don't use intermediate strings to filter false positives in gravity
  gravity.sh
Labels: PR: Approval Required

#5178 Use buildx to create docker test images
  test/tox.centos_8.ini
  test/tox.centos_9.ini
  test/tox.debian_10.ini
  test/tox.debian_11.ini
  test/tox.fedora_36.ini
  test/tox.fedora_37.ini
  test/tox.ubuntu_20.ini
  test/tox.ubuntu_22.ini
Labels: PR: Approval Required
