Repository pi-hole/pi-hole, pull requests merged in 2023-10, with the labels that each got.

#5417 Update references to web repo
  README.md
  advanced/Scripts/chronometer.sh
  advanced/Scripts/update.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/version.sh
  automated install/basic-install.sh
  manpages/pihole.8
Labels: internal

#5427 Allow pihole to access subdirs in /etc/pihole
  advanced/Templates/pihole-FTL-prestart.sh
Labels: PR: Approval Required, v6

#5423 Remove Chronometer
  .codespellignore
  advanced/Scripts/chronometer.sh
  advanced/bash-completion/pihole
  automated install/basic-install.sh
  manpages/pihole.8
  pihole
Labels: PR: Approval Required, v6

#5419 Set owner of gravity output files to pihole
  automated install/basic-install.sh
Labels: PR: Approval Required, v6

#5442 Avoid printing getFTLConfigValue return in statusFunc()
  pihole
Labels: v6

#5444 Logrotate config file needs to be owned by root
  advanced/Templates/pihole-FTL-prestart.sh
  automated install/basic-install.sh
Labels: v6

#5429 Remove temp dir created when downloading FTL
  automated install/basic-install.sh
Labels: v6

#5445 *BREAKING* Drop support for ancient ARMv4 and ARMv5
  automated install/basic-install.sh
  test/test_any_automated_install.py
Labels: v6

#5455 Fix gravity swapping
  gravity.sh
Labels: Bug: fixed, v6

#5451 Fix and simplify binary download
  automated install/basic-install.sh
  test/test_any_automated_install.py
Labels: Bug: fixed, v6

#5457 Use suffixed temp file
  gravity.sh
Labels: v6

#5461 Tweak Pi-hole's debug facility for v6
  advanced/Scripts/piholeDebug.sh
Labels: Debugging, v6
