Repository pi-hole/pi-hole, pull requests merged in 2023-09, with the labels that each got.

#5292 Do not try to remove stale label on PRs
  .github/workflows/stale.yml
Labels: internal, PR: Master branch

#5367 Remove fake user agent when downloading adlist
  gravity.sh
Labels: PR: Approval Required

#5366 Remove fake user agent when downloading adlists
  gravity.sh
Labels: PR: Approval Required

#5330 Add antigravity support to gravity
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/16_to_17.sql
  advanced/Templates/gravity.db.sql
  gravity.sh
Labels: Feature Request: Discourse, v6
