Repository pi-hole/pi-hole, pull requests merged in 2023-11, with the labels that each got.

#5468 Remove idn2 as punycode conversion is handled by FTL
  advanced/Scripts/query.sh
  automated install/basic-install.sh
Labels: v6

#5470 Start counting at postion 1
  advanced/Scripts/updatecheck.sh
Labels: v6

#5305 Check for valid OS via IPv4 and IPv6
  advanced/Scripts/piholeDebug.sh
  automated install/basic-install.sh
Labels: PR: Approval Required, v6

#5476 Tweak help text of pihole setpassword
  pihole
Labels: v6

#5478 pihole -d: Include pihole.toml only once
  advanced/Scripts/piholeDebug.sh
Labels: Debugging, v6

#5481 Improve v6 debug log and remove leftovers
  advanced/Scripts/piholeDebug.sh
  automated install/basic-install.sh
Labels: v6
