Repository pi-hole/pi-hole, pull requests merged in 2023-05, with the labels that each got.

#5266 Remove unused code from query.sh
  advanced/Scripts/query.sh
Labels: PR: Approval Required

#5273 Remove forgotten variables
  gravity.sh
Labels: PR: Approval Required

#5275 Use list parsing functionality of FTL
  advanced/Templates/gravity_copy.sql
  gravity.sh
Labels: Enhancement

#5284 Add Ubuntu 23 to test suite
  .github/workflows/test.yml
  test/_ubuntu_23.Dockerfile
  test/tox.ubuntu_23.ini
Labels: PR: Approval Required

#5288 Pi-hole v5.17
  .github/workflows/codeql-analysis.yml
  .github/workflows/stale.yml
  .github/workflows/stale_pr.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/Scripts/webpage.sh
  advanced/Templates/gravity_copy.sql
  automated install/basic-install.sh
  gravity.sh
  test/_fedora_38.Dockerfile
  test/_ubuntu_23.Dockerfile
  test/requirements.txt
  test/tox.fedora_38.ini
  test/tox.ubuntu_23.ini
Labels: Release

#5291 Fix Faulty Regex pattern in custom DNS domain validation
  advanced/Scripts/webpage.sh
  test/test_any_automated_install.py
Labels: PR: Approval Required, Bug: fixed

#5294 Fix gravity adlist status not being updated
  gravity.sh
Labels: Bug: fixed
