Repository pi-hole/pi-hole, pull requests merged in 2023-01, with the labels that each got.

#5112 Remove leftover from query.sh
  advanced/Scripts/query.sh
Labels: PR: Approval Required

#5105 Tweak get_directories_recursive
  test/test_any_automated_install.py
Labels: PR: Approval Required

#5098 Add action to close stale PR
  .github/workflows/stale_pr.yml
Labels: internal, PR: Master branch

#5093 Add pip ecosystem to dependabot
  .github/dependabot.yml
Labels: PR: Approval Required, internal, PR: Master branch

#5122 Remove fed 35 from test suite
  .github/workflows/test.yml
  test/_fedora_35.Dockerfile
Labels: internal

#5124 Remove leftover Fedora 35 tox file
  test/tox.fedora_35.ini
Labels: PR: Approval Required, internal

#5137 Run updatechecker after gravity
  automated install/basic-install.sh
Labels: PR: Approval Required

#5052 Cleanup if startup failed
  advanced/Templates/pihole-FTL.service
Labels: PR: Approval Required

#5128 Reduce number of false positives when gravity unable to import domains - change the wording of the output
  gravity.sh
Labels: PR: Approval Required

#5038 Always set lighttpd config dir permissions
  automated install/basic-install.sh
Labels: PR: Approval Required

#5141 Pi-hole core v5.15.1
  .github/workflows/test.yml
  advanced/Templates/pihole-FTL.service
  advanced/lighttpd.conf.debian
  advanced/lighttpd.conf.fedora
  advanced/pihole-admin.conf
  automated install/basic-install.sh
  gravity.sh
  test/_fedora_35.Dockerfile
  test/requirements.txt
  test/tox.fedora_35.ini
Labels: internal

#5150 Hotfix v5.15.3
  advanced/pihole-admin.conf
Labels: internal
