Repository pi-hole/pi-hole, pull requests merged in 2024-07, with the labels that each got.

#5694 Pi-hole core v5.18.3
  .github/workflows/codeql-analysis.yml
  .github/workflows/merge-conflict.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/1_to_2.sql
  advanced/Scripts/database_migration/gravity/2_to_3.sql
  advanced/Scripts/database_migration/gravity/3_to_4.sql
  advanced/Scripts/database_migration/gravity/4_to_5.sql
  advanced/Scripts/database_migration/gravity/7_to_8.sql
  advanced/Templates/gravity.db.sql
  advanced/Templates/logrotate
  advanced/bash-completion/pihole
  automated install/basic-install.sh
  gravity.sh
  manpages/pihole.8
  test/_fedora_40.Dockerfile
  test/_ubuntu_24.Dockerfile
  test/requirements.txt
  test/tox.centos_8.ini
  test/tox.fedora_40.ini
  test/tox.ubuntu_24.ini
Labels: PR: Approval Required, internal

#5698 Add protocol validation when downloading blocklist from URL
  gravity.sh
Labels: Security, Pi-hole v6.0

#5689 Finish core v6 implementation
  advanced/Scripts/api.sh
  advanced/Scripts/list.sh
  advanced/Scripts/pihole-reenable.sh
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/query.sh
  advanced/bash-completion/pihole
  manpages/pihole.8
  pihole
Labels: Testing Required, Pi-hole v6.0
