Repository pi-hole/pi-hole, pull requests merged in 2024-09, with the labels that each got.

#5743 Disable SELINUX on CentOS 9 test dockerfile
  test/_centos_9.Dockerfile
Labels: Pi-hole v6.0

#5747 Fix pihole status on not-ready states
  pihole
Labels: Bug: fixed, Pi-hole v6.0

#5749 remove development-v6 references from dependabot yml
  .github/dependabot.yml
Labels: internal

#5707 Remove obsolet Debian 10
  .github/workflows/test.yml
  test/_debian_10.Dockerfile
  test/tox.debian_10.ini
Labels: Pi-hole v6.0

#5613 Wait after restarting FTL before trying to check version
  advanced/Scripts/piholeCheckout.sh
Labels: Bug: fixed, Pi-hole v6.0

#5740 Add /etc/pihole/dnsmasq.conf to debug log (stripped-down version)
  advanced/Scripts/piholeDebug.sh
Labels: Debugging, Pi-hole v6.0

#5762 Grouped common dependencies of distros
  automated install/basic-install.sh
  automated install/uninstall.sh
Labels: Submitter Attention Required
