Repository pi-hole/pi-hole, pull requests merged in 2024-02, with the labels that each got.

#5563 Test ftl.pi-hole.net availability
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/update.sh
  automated install/basic-install.sh
Labels: Bug: fixed

#5526 Make IDs of anti-/gravity lists available in vw_(anti)gravity
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/database_migration/gravity/17_to_18.sql
  advanced/Scripts/database_migration/gravity/18_to_19.sql
  advanced/Templates/gravity.db.sql
  automated install/basic-install.sh
  gravity.sh
Labels: Pi-hole v6.0

#5480 Remove local.list and openVPN traces
  advanced/Scripts/piholeDebug.sh
  gravity.sh
Labels: Pi-hole v6.0

#5570 Merge development into development-v6 (with merge conflicts resolved)
  .github/workflows/stale.yml
  advanced/Scripts/query.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/version.sh
  automated install/basic-install.sh
  gravity.sh
Labels: internal, Pi-hole v6.0

#5573 Fix gravity
  gravity.sh
Labels: Bug: fixed, Pi-hole v6.0
