Repository pi-hole/pi-hole, pull requests merged in 2025-07, with the labels that each got.

#6337 Pi-hole Core v6.1.3
  .github/dependabot.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  advanced/Scripts/COL_TABLE
  advanced/Scripts/api.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/update.sh
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  pihole
  test/requirements.txt
  test/test_any_automated_install.py
Labels: Release, internal

#6319 Tweak ARP flushing function
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeNetworkFlush.sh
  advanced/bash-completion/pihole
  manpages/pihole.8
  pihole
Labels: PR: Approved, Dependent on Other Repo

#6351 Use true/false instead of 0/1 to represent bool
  pihole
Labels: PR: Approved

#6367 Revert "pihole api - use keepalive for curl queries"
  advanced/Scripts/api.sh
Labels: internal

#6368 Do not call pihole-FTL --config interactively
  advanced/Scripts/utils.sh
Labels: Bug: fixed
