Repository pi-hole/pi-hole, pull requests merged in 2025-01, with the labels that each got.

#5849 Improve lighttpd disabling
  automated install/basic-install.sh
Labels: Pi-hole v6.0

#5830 Explicitly migrate from v5 to v6
  automated install/basic-install.sh
Labels: Bug: fixed, Pi-hole v6.0

#5854 Remove unused code from debug log and skip some tests inside containers
  advanced/Scripts/piholeDebug.sh
  pihole
Labels: Pi-hole v6.0

#5818 Gravity database resilience
  advanced/Templates/gravity.db.sql
  gravity.sh
Labels: Enhancement, Bug: fixed, Pi-hole v6.0

#5868 Use a different method to identify if a gravity restore succeeded
  gravity.sh
Labels: Bug: fixed, Pi-hole v6.0
