Repository pi-hole/pi-hole, pull requests merged in 2025-02, with the labels that each got.

#5881 Fix counting of domains in the gravity summary
  gravity.sh
Labels: Bug: fixed, Pi-hole v6.0

#5867 Gravity: Use ETags
  gravity.sh
Labels: Pi-hole v6.0

#5869 Move gravity list cache into dedicated directory
  gravity.sh
Labels: Pi-hole v6.0

#5884 Show only enabled domains/regex in the final gravity message
  gravity.sh
Labels: Pi-hole v6.0

#5872 Decide if the content was changed *before* passing over to FTL
  gravity.sh
Labels: Pi-hole v6.0

#5888 Amend warning on gravity tree build failure
  gravity.sh
Labels: Pi-hole v6.0

#5903 Fix i386 fallback download
  automated install/basic-install.sh
Labels: Bug: fixed

#5975 Pi-hole Core v6.0.4
  automated install/basic-install.sh
  pihole
Labels: internal

#5977 Improve gravity on systems with low memory
  gravity.sh
Labels: Bug: fixed, PR: Approved
