Repository pi-hole/pi-hole, pull requests merged in 2025-04, with the labels that each got.

#6146 Revert #6137
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/query.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/version.sh
  advanced/Templates/pihole-FTL-poststop.sh
  advanced/Templates/pihole-FTL-prestart.sh
  advanced/Templates/pihole-FTL.service
  gravity.sh
Labels: internal

#6105 Move list parsing entirely into FTL
  gravity.sh
Labels: Enhancement

#6002 versions file should readable by others (make pihole -v work for non-root users)
  advanced/Templates/pihole-FTL-prestart.sh
Labels: Discussion

#6147 Shellcheck Tweaks
  .github/workflows/test.yml
  .shellcheckrc
  advanced/Scripts/database_migration/gravity-db.sh
  advanced/Scripts/list.sh
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/query.sh
  advanced/Scripts/update.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/utils.sh
  advanced/Scripts/version.sh
  advanced/Templates/pihole-FTL-poststop.sh
  advanced/Templates/pihole-FTL-prestart.sh
  advanced/Templates/pihole-FTL.service
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  pihole
Labels: PR: Approval Required, internal

#6155 Fix more shellcheck warnings
  .github/workflows/test.yml
  .shellcheckrc
  advanced/Scripts/api.sh
  advanced/Scripts/list.sh
  advanced/Scripts/piholeARPTable.sh
  advanced/Scripts/piholeCheckout.sh
  advanced/Scripts/piholeDebug.sh
  advanced/Scripts/piholeLogFlush.sh
  advanced/Scripts/query.sh
  advanced/Scripts/update.sh
  advanced/Scripts/updatecheck.sh
  advanced/Scripts/utils.sh
  advanced/Scripts/version.sh
  advanced/Templates/pihole-FTL-poststop.sh
  advanced/Templates/pihole-FTL-prestart.sh
  automated install/basic-install.sh
  automated install/uninstall.sh
  gravity.sh
  pihole
Labels: internal

#6113 Add ON DELETE CASCADE to FOREIGN KEY REFERENCES in gravity.db
  advanced/Templates/gravity.db.sql
Labels: Bug: fixed
